_wandb:
    value:
        cli_version: 0.23.1
        e:
            j47qqz7xxjrkx13eslja3retr2ma2hwm:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                codePath: Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                codePathLocal: src/mnist_project/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "435964870656"
                email: mathias.krois@gmail.com
                executable: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/.venv/bin/python3
                git:
                    commit: ac233ba7e0254d45f617ed926ee99de4528b188b
                    remote: https://github.com/mathiaskrois/DSP.git
                host: Mathiass-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                python: CPython 3.12.12
                root: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist
                startedAt: "2026-01-08T13:20:17.518206Z"
                writerId: j47qqz7xxjrkx13eslja3retr2ma2hwm
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
