_wandb:
    value:
        cli_version: 0.23.1
        e:
            rb2iqok72lll2ihe9uzmtz79318xko2b:
                codePath: Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                codePathLocal: train.py
                email: mathias.krois@gmail.com
                executable: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/.venv/bin/python
                git:
                    commit: ac233ba7e0254d45f617ed926ee99de4528b188b
                    remote: https://github.com/mathiaskrois/DSP.git
                host: Mathiass-MacBook-Pro-2.local
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                python: CPython 3.12.12
                root: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project
                startedAt: "2026-01-08T12:53:43.337845Z"
                writerId: rb2iqok72lll2ihe9uzmtz79318xko2b
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
