_wandb:
    value:
        cli_version: 0.23.1
        e:
            47goke96ahqfqdh4g1m27spskjyenimm:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "1073741824"
                codePath: src/mnist_project/train.py
                codePathLocal: src/mnist_project/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "444038590464"
                email: mathias.krois@gmail.com
                executable: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/.venv/bin/python3
                git:
                    commit: 5e27cc4f6998bce346534058650e56835c897f75
                    remote: https://github.com/mathiaskrois/mlops_mnist.git
                host: MacBookPro.localdomain
                memory:
                    total: "17179869184"
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                python: CPython 3.12.12
                root: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist
                startedAt: "2026-01-14T08:08:34.000218Z"
                writerId: 47goke96ahqfqdh4g1m27spskjyenimm
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
