_wandb:
    value:
        cli_version: 0.23.1
        e:
            vz6aciukb4bfoted38erxejaue6kgvoq:
                codePath: Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                codePathLocal: src/mnist_project/train.py
                email: mathias.krois@gmail.com
                executable: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/.venv/bin/python3
                git:
                    commit: ac233ba7e0254d45f617ed926ee99de4528b188b
                    remote: https://github.com/mathiaskrois/DSP.git
                host: MacBookPro.localdomain
                os: macOS-26.1-arm64-arm-64bit
                program: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist/src/mnist_project/train.py
                python: CPython 3.12.12
                root: /Users/mathiaskroismoller/Documents/DTU/Kanditat/2. Semester/MLOPS/mlops_mnist
                startedAt: "2026-01-12T09:17:37.310194Z"
                writerId: vz6aciukb4bfoted38erxejaue6kgvoq
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
